### ISSUE TITLE
URL of CVE has changed

### ISSUE THREAD

**Issue by HoffmannTom** [Jean13/CVE_Compare#1]
Please update the URL and filename in CVE_Compare.py to:

latest_file = "nvdcve-1.1-" + str(current_year) + ".json"
filename = "nvdcve-1.1-" + str(year) + ".json.zip"
url = "https://nvd.nist.gov/feeds/json/cve/1.1/" + filename

**Comment by Jean13** [comment]
Thanks for catching the update, Tom. Updated.
